clear

echo "                                                                         "
echo "                                                                         "
echo "                                                                         "
echo "                                     ▄▄▄      ▓█████▄  ███▄ ▄███▓ ▄▄▄     ▄▄▄█████▓"
echo "                                    ▒████▄    ▒██▀ ██▌▓██▒▀█▀ ██▒▒████▄   ▓  ██▒ ▓▒"
echo "                                    ▒██  ▀█▄  ░██   █▌▓██    ▓██░▒██  ▀█▄ ▒ ▓██░ ▒░"
echo "                                    ░██▄▄▄▄██ ░▓█▄   ▌▒██    ▒██ ░██▄▄▄▄██░ ▓██▓ ░ "
echo "                                     ▓█   ▓██▒░▒████▓ ▒██▒   ░██▒ ▓█   ▓██▒ ▒██▒ ░ "
echo "                                     ▒▒   ▓▒█░ ▒▒▓  ▒ ░ ▒░   ░  ░ ▒▒   ▓▒█░ ▒ ░░ "
echo "                                     ▒   ▒▒ ░ ░ ▒  ▒ ░  ░      ░  ▒   ▒▒ ░   ░  "
echo "                                    ░   ▒    ░ ░  ░ ░      ░     ░   ▒    ░   "
echo "                                        ░  ░   ░           ░         ░  ░   "
echo "                                             ░     "





python3 /home/ubuntu/Desktop/proxit3/BTC.py &
python3 /home/ubuntu/Desktop/proxit3/ETH.py &
python3 /home/ubuntu/Desktop/proxit3/BNB.py &
python3 /home/ubuntu/Desktop/proxit3/XRP.py &
python3 /home/ubuntu/Desktop/proxit3/ADA.py &
python3 /home/ubuntu/Desktop/proxit3/SOL.py &
python3 /home/ubuntu/Desktop/proxit3/DOGE.py &
python3 /home/ubuntu/Desktop/proxit3/MATIC.py &
python3 /home/ubuntu/Desktop/proxit3/DOT.py &
python3 /home/ubuntu/Desktop/proxit3/DAI.py &
python3 /home/ubuntu/Desktop/proxit3/SHIB.py &
python3 /home/ubuntu/Desktop/proxit3/TRX.py &
python3 /home/ubuntu/Desktop/proxit3/AVAX.py &
python3 /home/ubuntu/Desktop/proxit3/UNI.py &
python3 /home/ubuntu/Desktop/proxit3/WBTC.py &
python3 /home/ubuntu/Desktop/proxit3/LEO.py &
python3 /home/ubuntu/Desktop/proxit3/LTC.py &
python3 /home/ubuntu/Desktop/proxit3/ATOM.py &
python3 /home/ubuntu/Desktop/proxit3/LINK.py &
python3 /home/ubuntu/Desktop/proxit3/ETC.py &
python3 /home/ubuntu/Desktop/proxit3/XLM.py &
python3 /home/ubuntu/Desktop/proxit3/FTT.py &
python3 /home/ubuntu/Desktop/proxit3/NEAR.py &
python3 /home/ubuntu/Desktop/proxit3/CRO.py &
python3 /home/ubuntu/Desktop/proxit3/XMR.py &
python3 /home/ubuntu/Desktop/proxit3/ALGO.py &
python3 /home/ubuntu/Desktop/proxit3/BCH.py &
python3 /home/ubuntu/Desktop/proxit3/LUNC.py &
python3 /home/ubuntu/Desktop/proxit3/QNT.py &
python3 /home/ubuntu/Desktop/proxit3/FLOW.py &
python3 /home/ubuntu/Desktop/proxit3/VET.py &
python3 /home/ubuntu/Desktop/proxit3/TON.py &
python3 /home/ubuntu/Desktop/proxit3/APE.py &
python3 /home/ubuntu/Desktop/proxit3/FIL.py &
python3 /home/ubuntu/Desktop/proxit3/ICP.py &
python3 /home/ubuntu/Desktop/proxit3/HBAR.py &
python3 /home/ubuntu/Desktop/proxit3/EGLD.py &
python3 /home/ubuntu/Desktop/proxit3/XTZ.py &
python3 /home/ubuntu/Desktop/proxit3/MANA.py &
python3 /home/ubuntu/Desktop/proxit3/SAND.py &
python3 /home/ubuntu/Desktop/proxit3/CHZ.py &
python3 /home/ubuntu/Desktop/proxit3/EOS.py &
python3 /home/ubuntu/Desktop/proxit3/AAVE.py &
python3 /home/ubuntu/Desktop/proxit3/THETA.py &
python3 /home/ubuntu/Desktop/proxit3/AXS.py &
python3 /home/ubuntu/Desktop/proxit3/USDP.py &
python3 /home/ubuntu/Desktop/proxit3/OKB.py &
python3 /home/ubuntu/Desktop/proxit3/BSV.py &
python3 /home/ubuntu/Desktop/proxit3/TUSD.py &
python3 /home/ubuntu/Desktop/proxit3/MKR.py &
python3 /home/ubuntu/Desktop/proxit3/KCS.py &
python3 /home/ubuntu/Desktop/proxit3/ZEC.py &
python3 /home/ubuntu/Desktop/proxit3/USDD.py &
python3 /home/ubuntu/Desktop/proxit3/HT.py &
python3 /home/ubuntu/Desktop/proxit3/XEC.py &
python3 /home/ubuntu/Desktop/proxit3/MIOTA.py &
python3 /home/ubuntu/Desktop/proxit3/BTT.py &
python3 /home/ubuntu/Desktop/proxit3/USDN.py &
python3 /home/ubuntu/Desktop/proxit3/CAKE.py &
python3 /home/ubuntu/Desktop/proxit3/GRT.py &
python3 /home/ubuntu/Desktop/proxit3/NEO.py &
python3 /home/ubuntu/Desktop/proxit3/HNT.py &
python3 /home/ubuntu/Desktop/proxit3/KLAY.py &
python3 /home/ubuntu/Desktop/proxit3/FTM.py &
python3 /home/ubuntu/Desktop/proxit3/PAXG.py &
python3 /home/ubuntu/Desktop/proxit3/SNX.py &
python3 /home/ubuntu/Desktop/proxit3/RUNE.py &
python3 /home/ubuntu/Desktop/proxit3/NEXO.py &
python3 /home/ubuntu/Desktop/proxit3/GT.py &
python3 /home/ubuntu/Desktop/proxit3/DASH.py &
python3 /home/ubuntu/Desktop/proxit3/CRV.py &
python3 /home/ubuntu/Desktop/proxit3/BAT.py &
python3 /home/ubuntu/Desktop/proxit3/ENJ.py &
python3 /home/ubuntu/Desktop/proxit3/LDO.py &
python3 /home/ubuntu/Desktop/proxit3/STX.py &
python3 /home/ubuntu/Desktop/proxit3/KAVA.py &
python3 /home/ubuntu/Desktop/proxit3/COMP.py &
python3 /home/ubuntu/Desktop/proxit3/ZIL.py &
python3 /home/ubuntu/Desktop/proxit3/FEI.py &
python3 /home/ubuntu/Desktop/proxit3/RVN.py &
python3 /home/ubuntu/Desktop/proxit3/MINA.py &
python3 /home/ubuntu/Desktop/proxit3/WAVES.py &
python3 /home/ubuntu/Desktop/proxit3/XDC.py &
python3 /home/ubuntu/Desktop/proxit3/USDTC.py &
python3 /home/ubuntu/Desktop/proxit3/GMT.py &
python3 /home/ubuntu/Desktop/proxit3/TWT.py &
python3 /home/ubuntu/Desktop/proxit3/LRC.py &
python3 /home/ubuntu/Desktop/proxit3/DCR.py &
python3 /home/ubuntu/Desktop/proxit3/CVX.py &
python3 /home/ubuntu/Desktop/proxit3/CSPR.py &
python3 /home/ubuntu/Desktop/proxit3/XEM.py &
python3 /home/ubuntu/Desktop/proxit3/KSM.py &
python3 /home/ubuntu/Desktop/proxit3/CELO.py &
python3 /home/ubuntu/Desktop/proxit3/BTG.py &
python3 /home/ubuntu/Desktop/proxit3/ENS.py &
python3 /home/ubuntu/Desktop/proxit3/1INCH.py &
python3 /home/ubuntu/Desktop/proxit3/HOT.py &
python3 /home/ubuntu/Desktop/proxit3/LUNA.py &
python3 /home/ubuntu/Desktop/proxit3/RSR.py &
python3 /home/ubuntu/Desktop/proxit3/BNX.py &
python3 /home/ubuntu/Desktop/proxit3/GUSD.py &
python3 /home/ubuntu/Desktop/proxit3/ROSE.py &
python3 /home/ubuntu/Desktop/proxit3/YFI.py &
python3 /home/ubuntu/Desktop/proxit3/QTUM.py &
python3 /home/ubuntu/Desktop/proxit3/AR.py &
python3 /home/ubuntu/Desktop/proxit3/ANKR.py &
python3 /home/ubuntu/Desktop/proxit3/GNO.py &
python3 /home/ubuntu/Desktop/proxit3/GALA.py &
python3 /home/ubuntu/Desktop/proxit3/TFUEL.py &
python3 /home/ubuntu/Desktop/proxit3/KDA.py &
python3 /home/ubuntu/Desktop/proxit3/IOTX.py &
python3 /home/ubuntu/Desktop/proxit3/GLM.py &
python3 /home/ubuntu/Desktop/proxit3/BTRST.py &
python3 /home/ubuntu/Desktop/proxit3/JST.py &
python3 /home/ubuntu/Desktop/proxit3/CEL.py &
python3 /home/ubuntu/Desktop/proxit3/POLY.py &
python3 /home/ubuntu/Desktop/proxit3/ONE.py &
python3 /home/ubuntu/Desktop/proxit3/HIVE.py &
python3 /home/ubuntu/Desktop/proxit3/OMG.py &
python3 /home/ubuntu/Desktop/proxit3/LPT.py &
python3 /home/ubuntu/Desktop/proxit3/ZRX.py &
python3 /home/ubuntu/Desktop/proxit3/BAL.py &
python3 /home/ubuntu/Desktop/proxit3/FLUX.py &
python3 /home/ubuntu/Desktop/proxit3/IOST.py &
python3 /home/ubuntu/Desktop/proxit3/ICX.py &
python3 /home/ubuntu/Desktop/proxit3/BORA.py &
python3 /home/ubuntu/Desktop/proxit3/AMP.py &
python3 /home/ubuntu/Desktop/proxit3/XYM.py &
python3 /home/ubuntu/Desktop/proxit3/SRM.py &
python3 /home/ubuntu/Desktop/proxit3/KNC.py &
python3 /home/ubuntu/Desktop/proxit3/ONT.py &
python3 /home/ubuntu/Desktop/proxit3/OP.py &
python3 /home/ubuntu/Desktop/proxit3/GLMR.py &
python3 /home/ubuntu/Desktop/proxit3/CHSB.py &
python3 /home/ubuntu/Desktop/proxit3/STORJ.py &
python3 /home/ubuntu/Desktop/proxit3/WAXP.py &
python3 /home/ubuntu/Desktop/proxit3/SC.py &
python3 /home/ubuntu/Desktop/proxit3/WOO.py &
python3 /home/ubuntu/Desktop/proxit3/ZEN.py &
python3 /home/ubuntu/Desktop/proxit3/XCH.py &
python3 /home/ubuntu/Desktop/proxit3/SXP.py &
python3 /home/ubuntu/Desktop/proxit3/SUSHI.py &
python3 /home/ubuntu/Desktop/proxit3/IMX.py &
python3 /home/ubuntu/Desktop/proxit3/MXC.py &
python3 /home/ubuntu/Desktop/proxit3/AUDIO.py &
python3 /home/ubuntu/Desktop/proxit3/NFT.py &
python3 /home/ubuntu/Desktop/proxit3/UMA.py &
python3 /home/ubuntu/Desktop/proxit3/PLA.py &
python3 /home/ubuntu/Desktop/proxit3/SKL.py &
python3 /home/ubuntu/Desktop/proxit3/ABBC.py &
python3 /home/ubuntu/Desktop/proxit3/SCRT.py &
python3 /home/ubuntu/Desktop/proxit3/SLP.py &
python3 /home/ubuntu/Desktop/proxit3/DGB.py &
python3 /home/ubuntu/Desktop/proxit3/ELON.py &
python3 /home/ubuntu/Desktop/proxit3/INJ.py &
python3 /home/ubuntu/Desktop/proxit3/VGX.py &
python3 /home/ubuntu/Desktop/proxit3/CKB.py &
python3 /home/ubuntu/Desktop/proxit3/CVC.py &
python3 /home/ubuntu/Desktop/proxit3/LSK.py &
python3 /home/ubuntu/Desktop/proxit3/VLX.py &
python3 /home/ubuntu/Desktop/proxit3/PUNDIX.py &
python3 /home/ubuntu/Desktop/proxit3/COTI.py &
python3 /home/ubuntu/Desktop/proxit3/KEEP.py &
python3 /home/ubuntu/Desktop/proxit3/DAO.py &
python3 /home/ubuntu/Desktop/proxit3/REN.py &
python3 /home/ubuntu/Desktop/proxit3/MED.py &
python3 /home/ubuntu/Desktop/proxit3/RNDR.py &
python3 /home/ubuntu/Desktop/proxit3/CEEK.py &
python3 /home/ubuntu/Desktop/proxit3/REEF.py &
python3 /home/ubuntu/Desktop/proxit3/EWT.py &
python3 /home/ubuntu/Desktop/proxit3/PEOPLE.py &
python3 /home/ubuntu/Desktop/proxit3/BTCST.py &
python3 /home/ubuntu/Desktop/proxit3/WIN.py &
python3 /home/ubuntu/Desktop/proxit3/NU.py &
python3 /home/ubuntu/Desktop/proxit3/CELR.py &
python3 /home/ubuntu/Desktop/proxit3/SYS.py &
python3 /home/ubuntu/Desktop/proxit3/ONG.py &
python3 /home/ubuntu/Desktop/proxit3/XNO.py &
python3 /home/ubuntu/Desktop/proxit3/REQ.py &
python3 /home/ubuntu/Desktop/proxit3/DAG.py &
python3 /home/ubuntu/Desktop/proxit3/ORBS.py &
python3 /home/ubuntu/Desktop/proxit3/SPELL.py &
python3 /home/ubuntu/Desktop/proxit3/RLC.py &
python3 /home/ubuntu/Desktop/proxit3/OCEAN.py &
python3 /home/ubuntu/Desktop/proxit3/API3.py &
python3 /home/ubuntu/Desktop/proxit3/SNT.py &
python3 /home/ubuntu/Desktop/proxit3/TRIBE.py &
python3 /home/ubuntu/Desktop/proxit3/ARDR.py &
python3 /home/ubuntu/Desktop/proxit3/PYR.py &
python3 /home/ubuntu/Desktop/proxit3/FX.py &
python3 /home/ubuntu/Desktop/proxit3/UOS.py &
python3 /home/ubuntu/Desktop/proxit3/POWER.py &
python3 /home/ubuntu/Desktop/proxit3/ACA.py &
python3 /home/ubuntu/Desktop/proxit3/PROM.py &
python3 /home/ubuntu/Desktop/proxit3/DENT.py &
python3 /home/ubuntu/Desktop/proxit3/CHR.py &
python3 /home/ubuntu/Desktop/proxit3/MX.py &
python3 /home/ubuntu/Desktop/proxit3/%launcher%


